Repository kitodo/kitodo-production, pull requests merged in 2020-10, with the labels that each got.

#4010 Disable no-selection-option in selectOneMenus for mandatory metadata
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataTreeTable.xhtml
Labels: 3.x, bug

#4022 Fix duplicate key exception
  Kitodo-API/src/main/java/org/kitodo/api/Metadata.java
  Kitodo-Validation/src/main/java/org/kitodo/validation/metadata/MetadataValidation.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessFieldedMetadata.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/AddDocStrucTypeDialog.java
  Kitodo/src/main/java/org/kitodo/production/helper/metadata/legacytypeimplementations/LegacyLogicalDocStructHelper.java
  Kitodo/src/main/java/org/kitodo/production/process/NewspaperProcessesGenerator.java
Labels: 3.x, bug

#4048 Remove wrong static modifier from variables in QueryURLImport
  Kitodo-Query-URL-Import/src/main/java/org/kitodo/queryurlimport/QueryURLImport.java
Labels: 3.x, bug

#4040 Remove Primefaces filter workaround
  Kitodo/src/main/java/org/kitodo/production/forms/CurrentTaskForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/ProcessForm.java
  Kitodo/src/main/java/org/kitodo/production/model/LazyDTOModel.java
  Kitodo/src/main/java/org/kitodo/production/services/data/FilterService.java
  Kitodo/src/main/java/org/kitodo/production/services/data/ProcessService.java
  Kitodo/src/main/java/org/kitodo/production/services/data/TaskService.java
  Kitodo/src/main/webapp/WEB-INF/resources/js/filter.js
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processList.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/tasks/taskList.xhtml
  Kitodo/src/main/webapp/pages/processes.xhtml
  Kitodo/src/main/webapp/pages/tasks.xhtml
Labels: 3.x, bug, improvement

#4052 Fix wrong preservation of MediaUnits in combined structure tree
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/StructurePanel.java
Labels: 3.x, bug

#4057 Add filter field to userlist
  Kitodo-API/src/main/java/org/kitodo/exceptions/FilterException.java
  Kitodo-DataManagement/src/main/java/org/kitodo/data/database/persistence/BaseDAO.java
  Kitodo/src/main/java/org/kitodo/production/forms/ProcessForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/UserForm.java
  Kitodo/src/main/java/org/kitodo/production/model/LazyDTOModel.java
  Kitodo/src/main/java/org/kitodo/production/services/data/FilterService.java
  Kitodo/src/main/java/org/kitodo/production/services/data/UserService.java
  Kitodo/src/main/webapp/WEB-INF/resources/css/pattern-library.css
  Kitodo/src/main/webapp/pages/users.xhtml
Labels: 3.x, feature
