Repository kitodo/kitodo-production, pull requests merged in 2020-04, with the labels that each got.

#3367 Enable close button for sticky notifications
  Kitodo/src/main/webapp/WEB-INF/resources/css/pattern-library.css
Labels: 3.x

#3290 Mass import
  Kitodo/src/main/java/org/kitodo/exceptions/ImportException.java
  Kitodo/src/main/java/org/kitodo/production/forms/MassImportForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/ProcessForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/CreateProcessForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/TitleRecordLinkTab.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/DataEditorForm.java
  Kitodo/src/main/java/org/kitodo/production/helper/tasks/GeneratesNewspaperProcessesThread.java
  Kitodo/src/main/java/org/kitodo/production/helper/tasks/NewspaperMigrationTask.java
  Kitodo/src/main/java/org/kitodo/production/migration/NewspaperProcessesMigrator.java
  Kitodo/src/main/java/org/kitodo/production/process/NewspaperProcessesGenerator.java
  Kitodo/src/main/java/org/kitodo/production/services/data/ImportService.java
  Kitodo/src/main/java/org/kitodo/production/services/data/MassImportService.java
  Kitodo/src/main/java/org/kitodo/production/services/data/RulesetService.java
  Kitodo/src/main/java/org/kitodo/production/services/data/UserService.java
  Kitodo/src/main/webapp/WEB-INF/templates/includes/massImport/fileMassImport.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/massImport/textMassImport.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processFromTemplate/dataEdit.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/projects/projectList.xhtml
  Kitodo/src/test/java/org/kitodo/production/services/data/ImportServiceIT.java
  Kitodo/src/test/resources/kitodo_opac.xml
  Kitodo/src/test/resources/rulesets/ruleset_test.xml
  Kitodo/src/test/resources/sruTestRecord.xml
  Kitodo/src/test/resources/xslt/pica2kitodo.xsl
Labels: 3.x, enhancement

#3374 Update import module to make it usable for arbitrary search queries by URL
  Kitodo-API/src/main/java/org/kitodo/api/externaldatamanagement/SearchInterfaceType.java
  Kitodo-API/src/main/java/org/kitodo/config/OPACConfig.java
  Kitodo-Query-URL-Import/pom.xml
  Kitodo-Query-URL-Import/src/main/java/org/kitodo/queryurlimport/MarcResponseHandler.java
  Kitodo-Query-URL-Import/src/main/java/org/kitodo/queryurlimport/ModsResponseHandler.java
  Kitodo-Query-URL-Import/src/main/java/org/kitodo/queryurlimport/PicaResponseHandler.java
  Kitodo-Query-URL-Import/src/main/java/org/kitodo/queryurlimport/QueryURLImport.java
  Kitodo-Query-URL-Import/src/main/java/org/kitodo/queryurlimport/XmlResponseHandler.java
  Kitodo-Query-URL-Import/src/main/resources/META-INF/services/org.kitodo.api.externaldatamanagement.ExternalDataImportInterface
  Kitodo-Query-URL-Import/src/test/java/org/kitodo/queryurlimport/QueryURLImportTest.java
  Kitodo-Query-URL-Import/src/test/resources/kitodo_config.properties
  Kitodo-Query-URL-Import/src/test/resources/kitodo_opac.xml
  Kitodo-Query-URL-Import/src/test/resources/sruTestRecord.xml
  pom.xml
Labels: 3.x, enhancement

#3376 Add left padding to currentTaskEdit actions
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/currentTasksEdit/taskBoxActivities.xhtml
Labels: 3.x, bug

#3366 fix removing loose indexdata
  Kitodo/src/main/java/org/kitodo/production/forms/IndexingForm.java
  Kitodo/src/main/java/org/kitodo/production/helper/IndexWorker.java
  Kitodo/src/main/java/org/kitodo/production/services/data/base/SearchService.java
  Kitodo/src/main/java/org/kitodo/production/services/index/IndexAllThread.java
  Kitodo/src/main/java/org/kitodo/production/services/index/IndexingService.java
  Kitodo/src/test/java/org/kitodo/production/services/data/ProcessServiceIT.java
Labels: 3.x, bug

#3421 Update Chrome driver to version 81
  Kitodo/src/test/java/org/kitodo/selenium/testframework/helper/WebDriverProvider.java
Labels: 3.x

#3397 add table to pieChart
  Kitodo/src/main/java/org/kitodo/production/forms/ProcessForm.java
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processList.xhtml
Labels: 3.x

#3398 Set sort helper status on administrative task status manipulation
  Kitodo/src/main/java/org/kitodo/production/forms/ProcessForm.java
  Kitodo/src/main/java/org/kitodo/production/services/workflow/WorkflowControllerService.java
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processList.xhtml
Labels: 3.x, bug

#3399 Update icons on mass import buttons
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/massImport/fileMassImport.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/massImport/textMassImport.xhtml
Labels: 3.x, improvement

#3404 Fix 'metsFromKitodo.xml' test file
  Kitodo-DataFormat/src/main/java/org/kitodo/dataformat/access/DivXmlElementAccess.java
  Kitodo/src/test/resources/metadata/2/meta.xml
  Kitodo/src/test/resources/metsFromKitodo.xml
Labels: 3.x, legal

#3419 Add metadata to calendar
  Kitodo/src/main/java/org/kitodo/production/forms/CalendarForm.java
  Kitodo/src/main/java/org/kitodo/production/model/bibliography/course/Block.java
  Kitodo/src/main/java/org/kitodo/production/model/bibliography/course/Cell.java
  Kitodo/src/main/java/org/kitodo/production/model/bibliography/course/metadata/CountableMetadata.java
  Kitodo/src/main/java/org/kitodo/production/model/bibliography/course/metadata/IssueComparator.java
  Kitodo/src/main/java/org/kitodo/production/services/calendar/CalendarService.java
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/calendarEdit/calendarBlocks.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/calendarEdit/calendarDayDialog.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/calendarEdit/calendarDetails.xhtml
  Kitodo/src/main/webapp/pages/calendarEdit.xhtml
Labels: 3.x, feature

#3415 Import dialog
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/CreateProcessForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ImportDialog.java
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/massImport/fileMassImport.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/massImport/textMassImport.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processFromTemplate/dialogs/errorPopup.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processFromTemplate/dialogs/exemplarRecords.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processFromTemplate/dialogs/hitlistDialog.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processFromTemplate/dialogs/import.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processFromTemplate/dialogs/manyChildrenWarning.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processFromTemplate/import.xhtml
  Kitodo/src/main/webapp/pages/processFromTemplate.xhtml
Labels: 3.x, improvement

#3423 Skip docType validation on 'cancel' in AddDocStrucDialog
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/dialogs/addDocStrucType.xhtml
Labels: 3.x, bug

#3424 Translate and speed up statistical evaluation button
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processList.xhtml
Labels: 3.x, improvement

#3438 Fix download button in process list and task widget
  Kitodo/src/main/webapp/WEB-INF/templates/includes/desktop/tasksWidget.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processList.xhtml
Labels: 3.x, bug

#3439 Fix metadata editor link in searchResult page
  Kitodo/src/main/webapp/pages/searchResult.xhtml
Labels: 3.x, bug

#3442 don't render pdf export button
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processList.xhtml
Labels: 3.x, improvement

#3441 choose template for massImport
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/SelectTemplateDialogView.java
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processFromTemplate/dialogs/selectTemplate.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/projects/projectList.xhtml
Labels: 3.x, improvement

#3468 Use removeAll instead of loop
  Kitodo/src/main/java/org/kitodo/production/services/file/FileService.java
Labels: improvement

#3469 Improve toString
  Kitodo-DataManagement/src/main/java/org/kitodo/data/database/beans/BaseBean.java
  Kitodo-DataManagement/src/main/java/org/kitodo/data/database/beans/BaseTemplateBean.java
  Kitodo/src/main/java/org/kitodo/production/model/Subfolder.java
Labels: improvement

#3425 Move task filter actions to popup menu
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/webapp/WEB-INF/templates/includes/tasks/taskList.xhtml
  Kitodo/src/test/java/org/kitodo/selenium/testframework/pages/TasksPage.java
Labels: 3.x, improvement

#3458 Remove obsolete modules.xml
  Kitodo/src/main/resources/modules.xml
  docs/developer/gettingstarted/development-version.md
  docs/developer/gettingstarted/eclipse-windows.md
Labels: 3.x

#3459 Fix thumbnails not being displayed
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/GalleryPanel.java
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/gallery.xhtml
Labels: 3.x, bug

#3465 Ensure that blur event is dispatched when input loses focus
  Kitodo/src/main/webapp/WEB-INF/resources/js/metadata_editor.js
Labels: 3.x, bug

#3466 Scroll to selected thumbnail
  Kitodo/src/main/webapp/WEB-INF/resources/js/metadata_editor.js
Labels: 3.x, bug

#3473 Fix redirect when canceling after an OPAC search
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/CreateProcessForm.java
  Kitodo/src/main/webapp/pages/processFromTemplate.xhtml
Labels: 3.x, bug

#3475 Fix width of pulldown menus in metadata editor
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataTreeTable.xhtml
Labels: 3.x

#3493 redirect to desktop on 403
  Kitodo/src/main/webapp/WEB-INF/web.xml
  Kitodo/src/main/webapp/pages/error.xhtml
Labels: 3.x, improvement

#3495 Add cancel button to 'changeDocType' dialog
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/dialogs/changeDocStrucType.xhtml
Labels: 3.x, improvement

#3498 Fix required attribute of catalog selection
  Kitodo/src/main/webapp/WEB-INF/templates/includes/massImport/fileMassImport.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/massImport/textMassImport.xhtml
Labels: 3.x, bug

#3517 Fix initial doctype selection in 'addDocStrucTypeDialog'
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/AddDocStrucTypeDialog.java
Labels: 3.x, bug

#3510 Replace 'Goobi Identifier' with 'Kitodo Identifier' in dockets
  Kitodo-Docket/src/test/resources/docket.xsl
  Kitodo-Docket/src/test/resources/docket_multipage.xsl
  Kitodo/src/main/resources/docket.xsl
  Kitodo/src/main/resources/docket_multipage.xsl
  Kitodo/src/test/resources/xslt/docket.xsl
Labels: 3.x, bug

#3516 Hide 'delete' option from context menu for pages
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/structure.xhtml
Labels: 3.x, bug

#3525 Update docket test PDFs to include 'Kitodo Identifier'
  Kitodo-Docket/src/test/resources/docket.pdf
  Kitodo-Docket/src/test/resources/docket_multipage.pdf
Labels: 3.x, bug

#3521 Fix workflow exception thrown when unknown roles are assigned to tasks
  Kitodo/src/main/java/org/kitodo/production/workflow/model/Converter.java
  Kitodo/src/main/resources/messages/errors_de.properties
  Kitodo/src/main/resources/messages/errors_en.properties
Labels: 3.x, improvement

#3538 Deactivate 'change type' context menu option for pages
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/structure.xhtml
Labels: 3.x

#3539 Fix ReaderIT tests
  Kitodo/src/test/java/org/kitodo/production/workflow/model/ConverterIT.java
  Kitodo/src/test/java/org/kitodo/production/workflow/model/ReaderIT.java
Labels: 3.x, bug

#3549 Remove unneeded access to DataEditorService
  Kitodo/src/test/java/org/kitodo/production/helper/tasks/MigrationTaskIT.java
Labels: 3.x

#3557 Translate task processing status on task details page
  Kitodo/src/main/webapp/WEB-INF/templates/includes/currentTasksEdit/taskBoxDetails.xhtml
Labels: 3.x

#3558 Show error message for missing workflow title only once when saving
  Kitodo/src/main/java/org/kitodo/production/forms/TemplateForm.java
  Kitodo/src/main/resources/messages/errors_de.properties
  Kitodo/src/main/resources/messages/errors_en.properties
  Kitodo/src/main/webapp/WEB-INF/templates/baseEditView.xhtml
  Kitodo/src/main/webapp/pages/workflowEdit.xhtml
Labels: 3.x

#3559 Add action to toggle closed processes in process list
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processList.xhtml
Labels: 3.x

#3550 Prevent possible NPE
  Kitodo-DataManagement/src/main/java/org/kitodo/data/database/beans/User.java
  Kitodo/src/main/java/org/kitodo/production/helper/metadata/legacytypeimplementations/LegacyMetsModsDigitalDocumentHelper.java
  Kitodo/src/main/java/org/kitodo/production/helper/metadata/legacytypeimplementations/LegacyPrefsHelper.java
  Kitodo/src/main/java/org/kitodo/production/services/validation/MetadataValidationService.java
Labels: 3.x

#3553 use contains instead of startswith
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/dialogs/addDocStrucType.xhtml
Labels: 3.x, improvement

#3563 Add message key for automatic task
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
Labels: 3.x

#3564 URLDecode path to symbolic link before removal
  Kitodo-FileManagement/src/main/java/org/kitodo/filemanagement/FileManagement.java
Labels: 3.x, bug
