Repository kitodo/kitodo-production, pull requests merged in 2020-02, with the labels that each got.

#3151 Fix NPE when trying to automatically link new process to existing parent process
  Kitodo/src/main/java/org/kitodo/production/services/data/ImportService.java
  Kitodo/src/main/webapp/WEB-INF/templates/includes/desktop/projectsWidget.xhtml
Labels: 3.x, bug

#3157 Load one hit directly
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ImportTab.java
Labels: 3.x

#3165 Set default import depth to 1
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ImportTab.java
Labels: 3.x

#3167 Indent metadata group input fields on metadata import tab
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataTreeTable.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processFromTemplate/processMetadata.xhtml
Labels: 3.x

#3168 Fix column order of projects tab on page userEdit
  Kitodo/src/main/webapp/WEB-INF/templates/includes/userEdit/projectList.xhtml
Labels: 3.x

#3149 Query for confirmation before docstruct is deleted
  Goobi/pages/incMeta/Strukturdaten.jsp
  Goobi/src/messages/messages_de.properties
  Goobi/src/messages/messages_en.properties
Labels: 2.x

#3150 Use configured DIRECTORY_SUFFIX anywhere
  Goobi/src/de/sub/goobi/beans/Prozess.java
  Goobi/src/de/sub/goobi/export/dms/AutomaticDmsExportWithoutHibernate.java
  Goobi/src/de/sub/goobi/export/dms/DmsImportThread.java
  Goobi/src/de/sub/goobi/export/dms/ExportDms.java
  Goobi/src/de/sub/goobi/export/dms/ExportDms_CorrectRusdml.java
  Goobi/src/de/sub/goobi/forms/AdministrationForm.java
  Goobi/src/de/sub/goobi/forms/ProzesskopieForm.java
  Goobi/src/de/sub/goobi/helper/GoobiScript.java
  Goobi/src/org/goobi/production/cli/helper/CopyProcess.java
Labels: 2.x

#3146 Disable editing of active templates
  Kitodo/src/main/java/org/kitodo/production/forms/ProcessForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/TemplateForm.java
  Kitodo/src/main/java/org/kitodo/production/services/data/ProcessService.java
  Kitodo/src/main/java/org/kitodo/production/services/workflow/WorkflowControllerService.java
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/webapp/WEB-INF/templates/includes/projects/templateList.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/templateEdit/details.xhtml
  Kitodo/src/main/webapp/pages/templateEdit.xhtml
  Kitodo/src/test/java/org/kitodo/MockDatabase.java
  Kitodo/src/test/java/org/kitodo/production/process/ProcessGeneratorIT.java
  Kitodo/src/test/java/org/kitodo/production/services/data/ProjectServiceIT.java
  Kitodo/src/test/java/org/kitodo/production/services/data/TemplateServiceIT.java
  Kitodo/src/test/java/org/kitodo/production/services/migration/MigrationServiceIT.java
  Kitodo/src/test/java/org/kitodo/selenium/AddingST.java
  Kitodo/src/test/java/org/kitodo/selenium/EditingST.java
  Kitodo/src/test/java/org/kitodo/selenium/ListingST.java
  Kitodo/src/test/java/org/kitodo/selenium/MigrationST.java
  Kitodo/src/test/java/org/kitodo/selenium/testframework/pages/ProjectsPage.java
Labels: 3.x

#3147 No longer disclose credentials on the start screen
  Goobi/config/goobi_config.properties
  Goobi/src/messages/messages_de.properties
  Goobi/src/messages/messages_en.properties
Labels: 2.x

#3148 Remove default users, rename admin and LDAP group
  Goobi/setup/default.sql
Labels: 2.x

#3208 change to version 2.3.1
  build.xml
  deploy.xml
Labels: 2.x

#3207 Prevent error when no higherlevelidentifier is defined in ruleset
  Kitodo/src/main/java/org/kitodo/production/services/data/ImportService.java
Labels: 3.x, bug

#3163 Metadata editor keyboard shortcuts
  Kitodo-API/src/main/java/org/kitodo/api/dataformat/View.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/DataEditorForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/GalleryPanel.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/StructurePanel.java
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/resources/js/metadata_editor.js
  Kitodo/src/main/webapp/WEB-INF/resources/js/scroll.js
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/gallery.xhtml
Labels: 3.x, enhancement

#3200 Refactor CalendarForm classes
  Kitodo/src/main/java/org/kitodo/production/forms/CalendarForm.java
  Kitodo/src/main/java/org/kitodo/production/model/bibliography/course/Cell.java
Labels: 3.x

#3204 Prevent Zip Slip attack
  Kitodo-API/src/main/java/org/kitodo/serviceloader/KitodoServiceLoader.java
Labels: 3.x, security

#3205 Prevent potential XML External Entity attack
  Kitodo-SRU-Import/src/main/java/org/kitodo/sruimport/XmlResponseHandler.java
Labels: 3.x, security

#3213 resetting parentTempProcess for processes without a parent
  Kitodo/src/main/java/org/kitodo/production/services/data/ImportService.java
Labels: 3.x, bug

#3223 Fix one SeleniumTest and ignore another
  Kitodo/src/test/java/org/kitodo/selenium/MigrationST.java
  Kitodo/src/test/java/org/kitodo/selenium/WorkingST.java
  Kitodo/src/test/java/org/kitodo/selenium/testframework/pages/SystemPage.java
Labels: 3.x, bug

#3222 Add calendar frontend
  Kitodo/src/main/java/org/kitodo/production/forms/CalendarForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/GranularityForm.java
  Kitodo/src/main/java/org/kitodo/production/model/bibliography/course/Block.java
  Kitodo/src/main/java/org/kitodo/production/model/bibliography/course/Cell.java
  Kitodo/src/main/java/org/kitodo/production/model/bibliography/course/IndividualIssue.java
  Kitodo/src/main/java/org/kitodo/production/model/bibliography/course/Issue.java
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/resources/css/pattern-library.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/calendarEdit/calendarBlocks.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/calendarEdit/calendarDetails.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/calendarEdit/calendarSettingsDialog.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/calendarEdit/granularityDetails.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/calendarEdit/uploadFileDialog.xhtml
  Kitodo/src/main/webapp/pages/calendarEdit.xhtml
  Kitodo/src/test/java/org/kitodo/NewspaperCourse.java
Labels: 3.x

#3224 fix task indexing
  Kitodo/src/main/java/org/kitodo/production/forms/TemplateForm.java
  Kitodo/src/main/java/org/kitodo/production/services/data/TaskService.java
Labels: 3.x, bug

#3225 Better document LDAP parameters
  Goobi/config/goobi_config.properties
Labels: 2.x

#3226 Update ElasticSearch to last 5.6.x release
  pom.xml
Labels: 3.x, dependencies

#3232 Update calendar year on first appearance change
  Kitodo/src/main/java/org/kitodo/production/forms/CalendarForm.java
Labels: 3.x, enhancement

#3233 Disable ui while toggling weekdays in calendar form
  Kitodo/src/main/webapp/WEB-INF/templates/includes/calendarEdit/calendarBlocks.xhtml
Labels: 3.x, bug

#3234 add use to division
  Kitodo-API/src/main/java/org/kitodo/api/dataeditor/rulesetmanagement/FunctionalDivision.java
  Kitodo-API/src/main/java/org/kitodo/api/dataeditor/rulesetmanagement/RulesetManagementInterface.java
  Kitodo-DataEditor/src/main/java/org/kitodo/dataeditor/ruleset/RulesetManagement.java
  Kitodo-DataEditor/src/main/java/org/kitodo/dataeditor/ruleset/xml/Division.java
  Kitodo-DataEditor/src/test/java/org/kitodo/dataeditor/ruleset/RulesetManagementIT.java
  Kitodo-DataEditor/src/test/resources/ruleset.xsd
  Kitodo-DataEditor/src/test/resources/testAnExtensiveRulesetCanBeLoaded.xml
  Kitodo/src/test/java/org/kitodo/DummyRulesetManagement.java
Labels: 3.x, enhancement

#3236 Prevent NPE in ListColumnService
  Kitodo/src/main/java/org/kitodo/production/services/data/ListColumnService.java
Labels: 3.x, bug

#3238 fix param
  Kitodo/src/main/java/org/kitodo/production/forms/CalendarForm.java
  Kitodo/src/main/webapp/pages/calendarEdit.xhtml
Labels: 3.x, bug

#3239 disable massImport Button for release
  Kitodo/src/main/webapp/WEB-INF/templates/includes/projects/projectList.xhtml
Labels: 3.x

#3242 redirect to processlist
  Kitodo/src/main/java/org/kitodo/production/forms/CalendarForm.java
Labels: 3.x, enhancement

#3243 Update number of processes to be generated in calender confirm dialog
  Kitodo/src/main/java/org/kitodo/production/forms/CalendarForm.java
  Kitodo/src/main/webapp/WEB-INF/resources/css/pattern-library.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/calendarEdit/createProcessesConfirmDialog.xhtml
  Kitodo/src/main/webapp/pages/calendarEdit.xhtml
Labels: 3.x, bug

#3241 disable calendar icon conditionally
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/webapp/WEB-INF/resources/css/pattern-library.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processList.xhtml
Labels: 3.x, enhancement

#3245 Generate newspaper issue titles from parent process with date
  Kitodo/src/main/java/org/kitodo/production/process/NewspaperProcessesGenerator.java
Labels: 3.x, bug

#3247 add cache for ruleset reading
  Kitodo/src/main/java/org/kitodo/production/forms/ProcessForm.java
Labels: 3.x, enhancement

#3248 use workpieceproperty instead of reading meta.xml
  Kitodo/src/main/java/org/kitodo/production/forms/ProcessForm.java
Labels: 3.x, enhancement

#3249 Show tooltip of disabled calendar action in processList
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processList.xhtml
Labels: 3.x, bug
