Repository kitodo/kitodo-production, pull requests merged in 2020-03, with the labels that each got.

#3246 Show updated ORDER attribute after drag'n'drop of structural element in tree
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/StructurePanel.java
Labels: 3.x, bug

#3250 correct date setting
  Kitodo/src/main/java/org/kitodo/production/model/bibliography/course/Block.java
Labels: 3.x, bug

#3252 change version to 3.1.0
  Kitodo-API/pom.xml
  Kitodo-Command/pom.xml
  Kitodo-DataEditor/pom.xml
  Kitodo-DataFormat/pom.xml
  Kitodo-DataManagement/pom.xml
  Kitodo-Docket/pom.xml
  Kitodo-FileManagement/pom.xml
  Kitodo-ImageManagement/pom.xml
  Kitodo-LongTermPreservationValidation/pom.xml
  Kitodo-PersistentIdentifier/pom.xml
  Kitodo-SRU-Import/pom.xml
  Kitodo-Validation/pom.xml
  Kitodo-XML-SchemaConverter/pom.xml
  Kitodo/pom.xml
  pom.xml
Labels: 3.x

#3253 add snapshot to version
  Kitodo-API/pom.xml
  Kitodo-Command/pom.xml
  Kitodo-DataEditor/pom.xml
  Kitodo-DataFormat/pom.xml
  Kitodo-DataManagement/pom.xml
  Kitodo-Docket/pom.xml
  Kitodo-FileManagement/pom.xml
  Kitodo-ImageManagement/pom.xml
  Kitodo-LongTermPreservationValidation/pom.xml
  Kitodo-PersistentIdentifier/pom.xml
  Kitodo-SRU-Import/pom.xml
  Kitodo-Validation/pom.xml
  Kitodo-XML-SchemaConverter/pom.xml
  Kitodo/pom.xml
  pom.xml
Labels: 3.x

#3214 include fileupload
  Kitodo/pom.xml
  Kitodo/src/main/java/org/kitodo/production/forms/MassImportForm.java
  Kitodo/src/main/java/org/kitodo/production/services/ServiceManager.java
  Kitodo/src/main/java/org/kitodo/production/services/data/MassImportService.java
  Kitodo/src/main/webapp/WEB-INF/templates/includes/massImport/fileMassImport.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/massImport/textMassImport.xhtml
Labels: 3.x, enhancement

#3260 export parent
  Kitodo/src/main/java/org/kitodo/export/ExportMets.java
Labels: 3.x, enhancement

#3265 change colours to specification
  Kitodo/src/main/java/org/kitodo/config/enums/ParameterCore.java
  Kitodo/src/main/resources/kitodo_config.properties
  Kitodo/src/test/resources/selenium/resources/kitodo_config.properties
Labels: 3.x, enhancement

#3262 Update Hibernate to version 5.4.12
  pom.xml
Labels: 3.x, dependencies

#3267 Fix styling of physical metadata panel in metadata editor
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
Labels: 3.x, bug

#3273 Fix selection of MediaUnits through physical structure
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/StructurePanel.java
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/structure.xhtml
Labels: 3.x, bug

#3272 Restrict action columns to required width
  Kitodo/src/main/webapp/WEB-INF/resources/css/pattern-library.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processList.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/projects/docketList.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/projects/projectList.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/projects/rulesetList.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/projects/templateList.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/projects/workflowList.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/tasks/taskList.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/users/authorityList.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/users/clientList.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/users/ldapgroupList.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/users/ldapserverList.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/users/roleList.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/users/userList.xhtml
Labels: 3.x, bug

#3268 Add exported flag
  Kitodo-DataManagement/src/main/java/org/kitodo/data/database/beans/Process.java
  Kitodo-DataManagement/src/main/resources/db/migration/V2_91__Add_exported_flag.sql
  Kitodo/src/main/java/org/kitodo/export/ExportMets.java
  Kitodo/src/main/java/org/kitodo/production/services/data/ProcessService.java
  Kitodo/src/main/java/org/kitodo/production/services/data/TaskService.java
  Kitodo/src/test/java/org/kitodo/production/exporter/download/ExportMetsIT.java
Labels: 3.x, enhancement

#3277 Fix gallery update
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/structure.xhtml
Labels: 3.x, bug

#3227 Add option to import children of specific data record from OPAC
  Kitodo-API/src/main/java/org/kitodo/api/externaldatamanagement/ExternalDataImportInterface.java
  Kitodo-API/src/main/java/org/kitodo/config/OPACConfig.java
  Kitodo-API/src/main/java/org/kitodo/exceptions/CatalogException.java
  Kitodo-SRU-Import/src/main/java/org/kitodo/sruimport/SRUImport.java
  Kitodo-XML-SchemaConverter/src/main/java/org/kitodo/xmlschemaconverter/XMLSchemaConverter.java
  Kitodo/src/main/java/org/kitodo/production/forms/CalendarForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/CreateProcessForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ImportTab.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessFieldedMetadata.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessMetadataTab.java
  Kitodo/src/main/java/org/kitodo/production/model/LazyHitModel.java
  Kitodo/src/main/java/org/kitodo/production/process/ProcessValidator.java
  Kitodo/src/main/java/org/kitodo/production/services/data/ImportService.java
  Kitodo/src/main/java/org/kitodo/production/services/data/ProcessService.java
  Kitodo/src/main/resources/kitodo_opac.xml
  Kitodo/src/main/resources/messages/errors_de.properties
  Kitodo/src/main/resources/messages/errors_en.properties
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processEdit/hitlistDialog.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processFromTemplate/dialogs/errorPopup.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processFromTemplate/dialogs/manyChildrenWarning.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processFromTemplate/dialogs/progress.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processFromTemplate/import.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processList.xhtml
  Kitodo/src/main/webapp/pages/processFromTemplate.xhtml
Labels: 3.x, enhancement

#3280 Fix scrolling in structure tree during drag'n'drop
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/structure.xhtml
Labels: 3.x, bug

#3282 Improve design of 'createTemplatePopup' slightly
  Kitodo/src/main/webapp/WEB-INF/templates/includes/system/createTemplatePopup.xhtml
Labels: 3.x

#3287 Check for existing parent process during import even with import depth 1
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ImportTab.java
  Kitodo/src/main/java/org/kitodo/production/services/data/ImportService.java
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processList.xhtml
Labels: 3.x, enhancement

#3288 Update progress in task manager automatically
  Kitodo/src/main/webapp/WEB-INF/templates/includes/system/taskmanager.xhtml
Labels: 3.x, enhancement

#3283 Fix metadata synchronization with separate structure
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/DataEditorForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/GalleryPanel.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/StructurePanel.java
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/structure.xhtml
Labels: 3.x, bug

#3289 Expand all nodes in physical structure tree initially
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/StructurePanel.java
Labels: 3.x, enhancement

#3276 Not export links to unexported children
  Kitodo/src/main/java/org/kitodo/production/services/schema/SchemaService.java
Labels: 3.x

#3321 Save grouped metadata
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessFieldedMetadata.java
Labels: 3.x

#3322 Do not save empty metadata entries
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessTextMetadata.java
Labels: 3.x

#3325 Update error message for template title being in use
  Kitodo/src/main/java/org/kitodo/production/forms/BaseForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/ProjectForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/TemplateForm.java
  Kitodo/src/main/resources/messages/errors_de.properties
  Kitodo/src/main/resources/messages/errors_en.properties
Labels: 3.x
