Repository kitodo/kitodo-production, pull requests merged in 2020-08, with the labels that each got.

#3872 Prevent NumberFormatException in task filter
  Kitodo/src/main/java/org/kitodo/production/services/data/FilterService.java
Labels: 3.x, bug

#3878 Disable autocomplete for calendar input
  Kitodo/src/main/webapp/WEB-INF/templates/includes/calendarEdit/calendarBlocks.xhtml
Labels: 3.x, bug

#3879 Check block dates and update calendar when date is entered directly as text
  Kitodo/src/main/webapp/WEB-INF/templates/includes/calendarEdit/calendarBlocks.xhtml
Labels: 3.x, bug

#3881 Add hashCode() and equals()
  Goobi/src/org/goobi/io/SafeFile.java
Labels: 2.x

#3919 Prevent NPE
  Kitodo/src/main/java/org/kitodo/production/services/data/ProcessService.java
Labels: 3.x, bug

#3927 Disable deferred loading in metadata editor
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/gallery.xhtml
Labels: 3.x, bug

#3947 Fix equals method of MetadataEntry and MetadataGroup
  Kitodo-API/src/main/java/org/kitodo/api/MetadataEntry.java
  Kitodo-API/src/main/java/org/kitodo/api/MetadataGroup.java
Labels: 3.x, bug

#3942 Remove usages of org.joda.time
  Kitodo-DataEditor/pom.xml
  Kitodo-DataEditor/src/main/java/org/kitodo/dataeditor/JaxbXmlUtils.java
  Kitodo-DataEditor/src/test/java/org/kitodo/dataeditor/MetsKitodoWriterTest.java
  Kitodo-DataManagement/pom.xml
  Kitodo-DataManagement/src/test/java/org/kitodo/data/elasticsearch/index/type/ProcessTypeTest.java
  Kitodo-DataManagement/src/test/java/org/kitodo/data/elasticsearch/index/type/ProjectTypeTest.java
  Kitodo-DataManagement/src/test/java/org/kitodo/data/elasticsearch/index/type/TaskTypeTest.java
  Kitodo-DataManagement/src/test/java/org/kitodo/data/elasticsearch/index/type/TemplateTypeTest.java
  Kitodo/pom.xml
  Kitodo/src/main/java/org/kitodo/config/ConfigCore.java
  Kitodo/src/main/java/org/kitodo/production/helper/tasks/EmptyTask.java
  Kitodo/src/main/java/org/kitodo/production/helper/tasks/TaskSitter.java
  Kitodo/src/main/java/org/kitodo/production/interfaces/activemq/WebServiceResult.java
  Kitodo/src/main/java/org/kitodo/production/metadata/copier/ComposeFormattedRule.java
  Kitodo/src/main/java/org/kitodo/production/model/bibliography/Citation.java
  Kitodo/src/main/java/org/kitodo/production/security/SecuritySession.java
  Kitodo/src/main/java/org/kitodo/production/services/data/UserService.java
  Kitodo/src/main/java/org/kitodo/production/services/security/SessionService.java
  Kitodo/src/test/java/org/kitodo/MockDatabase.java
  pom.xml
Labels: 3.x

#3973 Fix 'required' attribute of title field on projectEdit page
  Kitodo/src/main/webapp/WEB-INF/templates/includes/projectEdit/projectEditDetail.xhtml
Labels: 3.x, bug

#3972 Display current tasks in process' rowExpansion
  Kitodo/src/main/java/org/kitodo/production/dto/TaskDTO.java
  Kitodo/src/main/java/org/kitodo/production/forms/ProcessForm.java
  Kitodo/src/main/java/org/kitodo/production/services/data/ProcessService.java
  Kitodo/src/main/java/org/kitodo/production/services/data/TaskService.java
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processList.xhtml
Labels: 3.x, improvement
