Repository kitodo/kitodo-production, pull requests merged in 2020-09, with the labels that each got.

#3985 Fix pattern for calendar input
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataTreeTable.xhtml
Labels: 3.x, bug

#3987 Fix conversion of json object to PropertyDTO
  Kitodo/src/main/java/org/kitodo/production/services/data/ProcessService.java
Labels: 3.x, bug

#4002 Fix updating process status after closing a task
  Kitodo/src/main/java/org/kitodo/production/services/workflow/WorkflowControllerService.java
Labels: 3.x, bug

#4001 Add option to import metadata from FTP server
  Kitodo-API/src/main/java/org/kitodo/api/externaldatamanagement/SearchInterfaceType.java
  Kitodo-API/src/main/java/org/kitodo/config/OPACConfig.java
  Kitodo-Query-URL-Import/pom.xml
  Kitodo-Query-URL-Import/src/main/java/org/kitodo/queryurlimport/QueryURLImport.java
  Kitodo-Query-URL-Import/src/main/java/org/kitodo/queryurlimport/XmlResponseHandler.java
  Kitodo/pom.xml
  Kitodo/src/main/java/org/kitodo/production/services/data/ImportService.java
  Kitodo/src/main/resources/kitodo_opac.xml
Labels: 3.x, feature

#4009 Fix error where httpClient variable could not be reassgned
  Kitodo-Query-URL-Import/src/main/java/org/kitodo/queryurlimport/QueryURLImport.java
Labels: 3.x, bug

#3993 Add option to add a preset for the current date in rulesets
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessDateMetadata.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessFieldedMetadata.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessTextMetadata.java
Labels: 3.x, improvement

#4004 Prevent NullPointerExceptions in form classes
  Kitodo/src/main/java/org/kitodo/production/forms/BaseForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/ProcessForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/ProjectForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/UserForm.java
Labels: 3.x, bug
