Repository kitodo/kitodo-production, pull requests merged in 2020-07, with the labels that each got.

#3798 Add filter to task list for tasks INWORK
  Kitodo/src/main/java/org/kitodo/production/forms/CurrentTaskForm.java
  Kitodo/src/main/java/org/kitodo/production/services/data/TaskService.java
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/webapp/WEB-INF/templates/includes/tasks/taskList.xhtml
  Kitodo/src/test/java/org/kitodo/selenium/testframework/pages/TasksPage.java
Labels: 3.x, feature

#3802 Prevent NPE on opening process in metadata editor with missing images
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/GalleryPanel.java
Labels: 3.x, bug

#3806 Add columns for last processed task
  Kitodo-DataManagement/src/main/resources/db/migration/V2_97__Add_columns_for_last_processed_task.sql
  Kitodo/src/main/java/org/kitodo/production/forms/ProcessForm.java
  Kitodo/src/main/java/org/kitodo/production/services/data/ProcessService.java
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processList.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/tasks/taskList.xhtml
Labels: 3.x

#3835 Temporary hotfix: ignore schema converter test
  Kitodo-XML-SchemaConverter/src/test/java/org/kitodo/xmlschemaconverter/XmlSchemaConverterTest.java
Labels: 3.x, bug

#3824 Fix wrong date format
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessTextMetadata.java
Labels: 3.x, bug

#3839 Fix selecting nodes in physical structure tree in metadata editor
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/DataEditorForm.java
Labels: 3.x, bug

#3788 Make shortcuts configurable per user
  Kitodo-DataManagement/src/main/java/org/kitodo/data/database/beans/User.java
  Kitodo-DataManagement/src/main/resources/db/migration/V2_98__Add_user_shortcuts.sql
  Kitodo/src/main/java/org/kitodo/production/forms/UserForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/DataEditorForm.java
  Kitodo/src/main/java/org/kitodo/production/services/data/UserService.java
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/resources/js/metadata_editor.js
  Kitodo/src/main/webapp/WEB-INF/resources/js/shortcuts.js
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/dialogs/help.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/userEdit/changeShortcutsPopup.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/userEdit/details.xhtml
  Kitodo/src/main/webapp/pages/metadataEditor.xhtml
  Kitodo/src/main/webapp/pages/userEdit.xhtml
Labels: 3.x, improvement

#3843 Fix some issues in form classes
  Kitodo/src/main/java/org/kitodo/production/forms/BatchForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/DocketForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/IndexingForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/MassImportForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/MigrationForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/ProjectForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/RulesetForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/SearchForm.java
  Kitodo/src/main/java/org/kitodo/production/services/data/ImportService.java
  Kitodo/src/main/resources/messages/errors_de.properties
  Kitodo/src/main/resources/messages/errors_en.properties
Labels: 3.x, improvement

#3816 Add option to navigate vertically in gallery
  Kitodo/src/main/java/org/kitodo/production/forms/UserForm.java
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/resources/js/metadata_editor.js
Labels: 3.x, improvement

#3844 Extend keyboard navigation in metadata editor
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/resources/js/metadata_editor.js
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/gallery.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/logicalStructure.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/physicalStructure.xhtml
  Kitodo/src/main/webapp/pages/metadataEditor.xhtml
Labels: 3.x, improvement

#3853 Remove old and obsolete dom4j 1.x dependency
  Kitodo/pom.xml
Labels: 3.x, security

#3861 Fix referer
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processActionsColumn.xhtml
Labels: 3.x, bug
