Repository kitodo/kitodo-production, pull requests merged in 2020-05, with the labels that each got.

#3573 Update log4j2
  pom.xml
Labels: 3.x

#3566 Cache images only until editor is closed
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/GalleryPanel.java
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/gallery.xhtml
Labels: 3.x, bug

#3574 Add 'Apply' button to pagination that keeps dialog open
  Kitodo/src/main/webapp/WEB-INF/resources/css/pattern-library.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/dialogs/pagination.xhtml
Labels: 3.x, improvement

#3585 Improve rendering of metadata panel in read only mode
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/resources/css/pattern-library.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/logicalMetadata.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/physicalMetadata.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataTreeTable.xhtml
Labels: 3.x, improvement

#3560 Update KitodoScript parameter for 'addRole'
  Kitodo/src/main/java/org/kitodo/production/services/command/KitodoScriptService.java
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/executeScriptSelectedPopup.xhtml
Labels: 3.x, bug

#3591 Rename missing steptitle to tasktitle parameters
  Kitodo/src/test/java/org/kitodo/production/services/command/KitodoScriptServiceIT.java
Labels: 3.x

#3608 Add missing import
  Kitodo/src/main/java/org/kitodo/production/services/validation/MetadataValidationService.java
Labels: 3.x, bug

#3610 Replace generic namespace prefixes
  Kitodo-DataFormat/pom.xml
  Kitodo-DataFormat/src/main/resources/xjb/kitodo.xjb
  Kitodo-DataFormat/src/main/resources/xjb/mets.xjb
Labels: 3.x, blocking, bug

#3611 Preserve and update metadata panel on page select in gallery
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/GalleryPanel.java
Labels: 3.x, bug

#3622 Adjust tests and resource files to new namespace prefixes
  Kitodo/src/test/java/org/kitodo/production/exporter/download/ExportMetsIT.java
  Kitodo/src/test/resources/metadata/10/meta.xml
  Kitodo/src/test/resources/metadata/testmetaNewFormat.xml
  Kitodo/src/test/resources/metadata/testmetaOldFormat.xml
  Kitodo/src/test/resources/testmetaOldFormat.xml
Labels: 3.x, bug

#3624 Fix Selenium tests
  Kitodo/src/test/java/org/kitodo/selenium/testframework/pages/ExtendedSearchPage.java
  Kitodo/src/test/java/org/kitodo/selenium/testframework/pages/ProcessFromTemplatePage.java
  Kitodo/src/test/resources/scripts/not_working_script.sh
  Kitodo/src/test/resources/scripts/script_createDirMeta.sh
  Kitodo/src/test/resources/scripts/script_createDirUserHome.sh
Labels: 3.x

#3626 Prevent ClassCastException in MetadataEditor
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataTreeTable.xhtml
Labels: 3.x, bug

#3628 Correction marker
  Kitodo-DataManagement/src/main/java/org/kitodo/data/database/enums/CorrectionComments.java
  Kitodo-DataManagement/src/main/resources/db/migration/V2_94__Add_correctionMessage_list_columns.sql
  Kitodo/src/main/java/org/kitodo/production/forms/CurrentTaskForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/ProcessForm.java
  Kitodo/src/main/java/org/kitodo/production/services/data/ProcessService.java
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processList.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/tasks/taskList.xhtml
Labels: 3.x, feature

#3631 Automatic MediaUnit selection
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/AddDocStrucTypeDialog.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/StructurePanel.java
  Kitodo/src/main/webapp/WEB-INF/resources/css/pattern-library.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/dialogs/addMediaUnit.xhtml
Labels: 3.x, bug

#3638 Show exception details on error page
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/pages/error.xhtml
Labels: 3.x, improvement

#3639 Reset password in UserForm before creating new user
  Kitodo/src/main/java/org/kitodo/production/forms/UserForm.java
Labels: 3.x, bug

#3644 Disable physical structure trees context menu during AJAX requests
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/structure.xhtml
Labels: 3.x, improvement

#3668 Use Chrome 83.
  Kitodo/src/test/java/org/kitodo/selenium/testframework/helper/WebDriverProvider.java
Labels: 3.x

#3667 Skip form validation when enabling 'save' button in UserEdit
  Kitodo/src/main/webapp/pages/userEdit.xhtml
Labels: 3.x, improvement

#3689 Expand correct metadata panel automatically
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/resources/js/metadata_editor.js
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/logicalStructure.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/paginationControls.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/physicalStructure.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/structure.xhtml
  Kitodo/src/main/webapp/pages/metadataEditor.xhtml
Labels: 3.x, improvement

#3690 Improve comments
  Kitodo/src/main/java/org/kitodo/production/forms/CommentForm.java
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/resources/css/pattern-library.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/comments/comments.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/comments/newCommentDialog.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/taskBatchEdit/taskEditActions.xhtml
  Kitodo/src/main/webapp/pages/currentTasksEdit.xhtml
  Kitodo/src/main/webapp/pages/metadataEditor.xhtml
Labels: 3.x, improvement

#3706 Hotfix: Fix context menu in structure trees
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/logicalStructure.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/physicalStructure.xhtml
Labels: 3.x, blocking, bug
