Repository kitodo/kitodo-production, pull requests merged in 2021-04, with the labels that each got.

#4328 Add path support for elastic search
  Kitodo-DataManagement/src/main/java/org/kitodo/data/elasticsearch/KitodoRestClient.java
  Kitodo/src/main/resources/kitodo_config.properties
  Kitodo/src/test/resources/kitodo_config.properties
  Kitodo/src/test/resources/scripts/script_createDirMeta.sh
  Kitodo/src/test/resources/selenium/resources/kitodo_config.properties
Labels: 3.x

#4324 Display 'correction K' on desktop process widget
  Kitodo/src/main/java/org/kitodo/production/forms/DesktopForm.java
  Kitodo/src/main/webapp/WEB-INF/templates/includes/desktop/processesWidget.xhtml
Labels: 3.x, improvement

#4351 Fix flyway migration
  Kitodo-DataManagement/src/main/resources/db/migration/V2_103__Rename_list_column_user_active_to_logged_in.sql
Labels: 3.x

#4349 Fix filter removal
  Kitodo/src/main/java/org/kitodo/production/services/data/UserService.java
Labels: 3.x, bug

#4354 Deactivate 'unassign' button after unassigning tasks
  Kitodo/src/main/webapp/WEB-INF/templates/includes/users/userList.xhtml
Labels: 3.x, bug
