Repository kitodo/kitodo-production, pull requests merged in 2021-06, with the labels that each got.

#4470 Fix child process import via SRU interfaces
  Kitodo-API/src/main/java/org/kitodo/api/externaldatamanagement/SearchInterfaceType.java
  Kitodo-Query-URL-Import/src/main/java/org/kitodo/queryurlimport/QueryURLImport.java
Labels: 3.x, bug

#4488 Add basic authentication option to query import
  Kitodo-API/src/main/java/org/kitodo/config/OPACConfig.java
  Kitodo-Query-URL-Import/src/main/java/org/kitodo/queryurlimport/QueryURLImport.java
Labels: 3.x, improvement

#4501 fix lockException
  Kitodo/src/main/java/org/kitodo/production/forms/TemplateForm.java
Labels: documentation

#4512 Hide process link option with selected pages
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/dialogs/addDocStrucType.xhtml
Labels: 3.x, improvement

#4524 Show error messages only once instead of twice
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/PaginationPanel.java
  Kitodo/src/main/webapp/WEB-INF/templates/baseEditView.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/baseListView.xhtml
  Kitodo/src/main/webapp/pages/desktop.xhtml
  Kitodo/src/main/webapp/pages/workflowEdit.xhtml
Labels: 3.x, improvement
