Repository kitodo/kitodo-production, pull requests merged in 2022-04, with the labels that each got.

#5052 Fix focus marker moving content
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
Labels: 3.x

#5071 Check locale support via FacesContext
  Kitodo/src/main/java/org/kitodo/production/helper/LocaleHelper.java
Labels: 3.x, improvement

#5039 Import metadata from mass import CSV files
  Kitodo/src/main/java/org/kitodo/production/forms/CsvCell.java
  Kitodo/src/main/java/org/kitodo/production/forms/CsvRecord.java
  Kitodo/src/main/java/org/kitodo/production/forms/MassImportForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/TemplateForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/MetadataImportDialog.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessFieldedMetadata.java
  Kitodo/src/main/java/org/kitodo/production/forms/massimport/AddMetadataDialog.java
  Kitodo/src/main/java/org/kitodo/production/forms/massimport/MassImportForm.java
  Kitodo/src/main/java/org/kitodo/production/helper/Helper.java
  Kitodo/src/main/java/org/kitodo/production/helper/SearchResultGeneration.java
  Kitodo/src/main/java/org/kitodo/production/services/data/ImportService.java
  Kitodo/src/main/java/org/kitodo/production/services/data/MassImportService.java
  Kitodo/src/main/java/org/kitodo/production/services/data/ProcessService.java
  Kitodo/src/main/resources/messages/errors_de.properties
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/resources/css/pattern-library.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/massImport/dialogs/addMetadata.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/massImport/dialogs/massImportProgress.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/massImport/dialogs/massImportResults.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/massImport/fileMassImport.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/massImport/massImportTab.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/massImport/textMassImport.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/projects/projectList.xhtml
  Kitodo/src/main/webapp/pages/massImport.xhtml
  Kitodo/src/test/java/org/kitodo/production/services/data/ImportServiceIT.java
Labels: feature, 3.x

#5088 Update log4j to 2.17.2 (security fix)
  pom.xml
Labels: 3.x, security fix

#5089 Update commons-io to 2.11.0 (security fix)
  pom.xml
Labels: 3.x, security fix

#5092 Update spring security to 5.6.3 (security fix)
  Kitodo-API/pom.xml
  pom.xml
Labels: 3.x, security fix
