Repository kitodo/kitodo-production, pull requests merged in 2023-08, with the labels that each got.

#5741 Change version 'org.apache.xmlgraphics' to '2.8' and add removed depe…
  Kitodo-Docket/pom.xml
  Kitodo/pom.xml
  pom.xml
Labels: dependencies, security vulnerability

#5742 [3.5] Change version 'org.apache.xmlgraphics' to '2.8' and add removed depe…
  Kitodo-Docket/pom.xml
  Kitodo/pom.xml
  pom.xml
Labels: dependencies

#5701 Rename media files corresponding to their order value
  Kitodo-API/src/main/java/org/kitodo/api/dataformat/Workpiece.java
  Kitodo-DataManagement/src/main/java/org/kitodo/data/database/beans/Project.java
  Kitodo-DataManagement/src/main/resources/db/migration/V2_124__Add_permission_to_rename_media.sql
  Kitodo/src/main/java/org/kitodo/production/controller/SecurityAccessController.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/DataEditorForm.java
  Kitodo/src/main/java/org/kitodo/production/services/file/FileService.java
  Kitodo/src/main/java/org/kitodo/production/services/security/SecurityAccessService.java
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/resources/js/metadata_editor.js
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/dialogs/renamingMediaResults.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/header.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/projectEdit/projectEditDetail.xhtml
  Kitodo/src/main/webapp/pages/metadataEditor.xhtml
  Kitodo/src/test/java/org/kitodo/MockDatabase.java
  Kitodo/src/test/java/org/kitodo/production/forms/ClientFormIT.java
  Kitodo/src/test/java/org/kitodo/production/services/data/AuthorityServiceIT.java
  Kitodo/src/test/java/org/kitodo/production/services/data/RoleServiceIT.java
  Kitodo/src/test/java/org/kitodo/production/services/security/SecurityAccessServiceIT.java
  Kitodo/src/test/java/org/kitodo/selenium/MetadataST.java
  Kitodo/src/test/java/org/kitodo/selenium/testframework/pages/MetadataEditorPage.java
  Kitodo/src/test/resources/metadata/testRenameMediaMeta.xml
Labels: feature

#5674 Renames variables ending in "interface" because they hold an instance
  Kitodo-DataEditor/src/main/java/org/kitodo/dataeditor/ruleset/Rule.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/AddDocStrucTypeDialog.java
  Kitodo/src/main/java/org/kitodo/production/helper/ProcessHelper.java
  Kitodo/src/main/java/org/kitodo/production/helper/metadata/legacytypeimplementations/LegacyMetadataHelper.java
  Kitodo/src/main/java/org/kitodo/production/metadata/MetadataEditor.java
  Kitodo/src/main/java/org/kitodo/production/services/command/CommandService.java
  Kitodo/src/main/java/org/kitodo/production/services/data/ImportService.java
  Kitodo/src/test/java/org/kitodo/production/helper/ProcessHelperIT.java
  Kitodo/src/test/java/org/kitodo/production/process/ProcessValidatorIT.java
  Kitodo/src/test/java/org/kitodo/production/process/TitleGeneratorTest.java
  Kitodo/src/test/java/org/kitodo/utils/ProcessTestUtils.java
Labels: improvement

#5744 Strip BOM character from string before performing XML transformation
  Kitodo-XML-SchemaConverter/src/main/java/org/kitodo/xmlschemaconverter/XMLSchemaConverter.java
Labels: bug

#5753 Fix cleaning up of MigrationST test files
  Kitodo/src/test/java/org/kitodo/selenium/MigrationST.java
  Kitodo/src/test/java/org/kitodo/selenium/testframework/pages/WorkflowEditPage.java
Labels: improvement

#5759 Fix retrieval of Chrome driver for Selenium tests
  Kitodo/src/test/java/org/kitodo/selenium/testframework/Browser.java
  Kitodo/src/test/java/org/kitodo/selenium/testframework/helper/WebDriverProvider.java
Labels: bug
