Repository kitodo/kitodo-production, pull requests merged in 2023-10, with the labels that each got.

#5657 Task action processor
  Kitodo-DataManagement/src/main/java/org/kitodo/data/database/enums/TaskEditType.java
  Kitodo-DataManagement/src/main/java/org/kitodo/data/database/persistence/CommentDAO.java
  Kitodo/src/main/java/org/kitodo/config/enums/ParameterCore.java
  Kitodo/src/main/java/org/kitodo/exceptions/ProcessorException.java
  Kitodo/src/main/java/org/kitodo/production/forms/CommentForm.java
  Kitodo/src/main/java/org/kitodo/production/interfaces/activemq/ActiveMQDirector.java
  Kitodo/src/main/java/org/kitodo/production/interfaces/activemq/ActiveMQProcessor.java
  Kitodo/src/main/java/org/kitodo/production/interfaces/activemq/FinalizeStepProcessor.java
  Kitodo/src/main/java/org/kitodo/production/interfaces/activemq/TaskAction.java
  Kitodo/src/main/java/org/kitodo/production/interfaces/activemq/TaskActionProcessor.java
  Kitodo/src/main/java/org/kitodo/production/services/data/CommentService.java
  Kitodo/src/main/java/org/kitodo/production/services/workflow/WorkflowControllerService.java
  Kitodo/src/main/resources/kitodo_config.properties
  Kitodo/src/test/java/org/kitodo/production/interfaces/activemq/TaskActionProcessorIT.java
  Kitodo/src/test/java/org/kitodo/production/services/workflow/WorkflowControllerServiceIT.java
Labels: feature

#5698 Unrender options without function during advanced pagination
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/PaginationPanel.java
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/dialogs/pagination.xhtml
Labels: improvement

#5684 Remove the OCR interface
  Kitodo-API/src/main/java/org/kitodo/api/ocr/FileProperty.java
  Kitodo-API/src/main/java/org/kitodo/api/ocr/FileResult.java
  Kitodo-API/src/main/java/org/kitodo/api/ocr/OCRInput.java
  Kitodo-API/src/main/java/org/kitodo/api/ocr/OCRResult.java
  Kitodo-API/src/main/java/org/kitodo/api/ocr/OpticalCharacterRecognitionInterface.java
  Kitodo-API/src/main/java/org/kitodo/api/ocr/State.java
Labels: improvement

#5685 Make individual terms in process properties searchable
  Kitodo/src/main/java/org/kitodo/production/services/data/ProcessService.java
Labels: feature

#5765 Fix process selection st
  Kitodo/src/test/java/org/kitodo/selenium/ProcessesSelectingST.java
Labels: bug

#5745 Sort template projects by title
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/SelectProjectDialogView.java
  Kitodo/src/main/java/org/kitodo/production/services/data/ProjectService.java
  Kitodo/src/main/java/org/kitodo/production/services/data/TemplateService.java
  Kitodo/src/test/java/org/kitodo/production/services/data/ProjectServiceIT.java
Labels: bug

#5679 Improve correction icon
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/resources/messages/messages_es.properties
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/base/commentTooltip.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/comments/comments.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/comments/newCommentDialog.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/currentTasksEdit/taskBoxActivities.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/desktop/processesWidget.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processList.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/taskBatchEdit/taskEditActions.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/tasks/taskList.xhtml
Labels: improvement

#5747 Print comments onto docket
  Kitodo-API/src/main/java/org/kitodo/api/docket/DocketData.java
  Kitodo-Docket/src/main/java/org/kitodo/docket/ExportXmlLog.java
  Kitodo-Docket/src/test/java/org/kitodo/docket/DocketDataGenerator.java
  Kitodo-Docket/src/test/resources/docket_multipage.xsl
  Kitodo/src/main/java/org/kitodo/production/services/data/ProcessService.java
  Kitodo/src/main/resources/docket.xsl
  Kitodo/src/main/resources/docket_multipage.xsl
Labels: bug

#5818 [3.6] Update org.json library to fix security issue
  .github/workflows/main.yml
  pom.xml
Labels: dependencies
