Repository kitodo/kitodo-production, pull requests merged in 2023-07, with the labels that each got.

#5708 Improve layout of 'upload media' dialog
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/dialogs/uploadFile.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/gallery.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/logicalStructure.xhtml
Labels: improvement

#5694 Fix order of logical and physical divisions
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/AddDocStrucTypeDialog.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/StructurePanel.java
  Kitodo/src/main/java/org/kitodo/production/metadata/MetadataEditor.java
Labels: bug

#5719 fix: pom.xml to reduce vulnerabilities
  pom.xml
Labels: security

#5704 Improve layout of parsed filters
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
Labels: bug, search
