Repository kitodo/kitodo-production, pull requests merged in 2024-02, with the labels that each got.

#5901 [3.6] prevent npe helper
  Kitodo/src/main/java/org/kitodo/production/helper/Helper.java
Labels: bug

#5902 [3.6] handle missing meta xml
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/DataEditorForm.java
  Kitodo/src/main/resources/messages/errors_de.properties
  Kitodo/src/main/resources/messages/errors_en.properties
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/dialogs/errorLoadingMetadataDialog.xhtml
  Kitodo/src/main/webapp/pages/metadataEditor.xhtml
Labels: bug

#5917 [3.6] Update spring security
  pom.xml
Labels: security, dependencies

#5903 Adds a way to import processes that only exist as files
  Kitodo-API/src/main/java/org/kitodo/api/validation/metadata/MetadataValidationInterface.java
  Kitodo-Validation/src/main/java/org/kitodo/validation/metadata/MetadataValidation.java
  Kitodo/src/main/java/org/kitodo/production/helper/Helper.java
  Kitodo/src/main/java/org/kitodo/production/services/command/ImportProcesses.java
  Kitodo/src/main/java/org/kitodo/production/services/command/ImportingProcess.java
  Kitodo/src/main/java/org/kitodo/production/services/command/KitodoScriptService.java
  Kitodo/src/main/java/org/kitodo/production/services/validation/MetadataValidationService.java
  Kitodo/src/main/resources/messages/errors_de.properties
  Kitodo/src/main/resources/messages/errors_en.properties
  Kitodo/src/main/resources/messages/errors_es.properties
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/resources/messages/messages_es.properties
  Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/executeScriptSelectedPopup.xhtml
  Kitodo/src/test/java/org/kitodo/production/services/command/ImportProcessesIT.java
  Kitodo/src/test/resources/ImportProcessesIT/p1_valid/meta.xml
  Kitodo/src/test/resources/ImportProcessesIT/p1c1_valid/images/17_123_0001_media/00000001.jpg
  Kitodo/src/test/resources/ImportProcessesIT/p1c1_valid/meta.xml
  Kitodo/src/test/resources/ImportProcessesIT/p1c2_valid/images/17_123_0002_media/00000001.jpg
  Kitodo/src/test/resources/ImportProcessesIT/p1c2_valid/meta.xml
  Kitodo/src/test/resources/ImportProcessesIT/p2_parentMissingAChild/meta.xml
  Kitodo/src/test/resources/ImportProcessesIT/p2c1_valid/meta.xml
  Kitodo/src/test/resources/ImportProcessesIT/p3_not-valid/meta.xml
  Kitodo/src/test/resources/ImportProcessesIT/p3c1_valid/meta.xml
  Kitodo/src/test/resources/ImportProcessesIT/p4_valid_butChildIsNot/meta.xml
  Kitodo/src/test/resources/ImportProcessesIT/p4c1_not-valid/meta.xml
  Kitodo/src/test/resources/rulesets/ImportProcessesIT.xml
Labels: feature

#5931 Assign ID to logical divisions in imported METS files which don't have one
  Kitodo-DataFormat/src/main/java/org/kitodo/dataformat/access/DivXmlElementAccess.java
Labels: blocking

#5938 Fix type comparison security issue
  Kitodo/src/main/java/org/kitodo/production/helper/SearchResultGeneration.java
Labels: security

#5941 Use secure random generator on string generation
  Kitodo/src/test/java/org/kitodo/selenium/testframework/generators/UserGenerator.java
Labels: security

#5940 Fix DTD security issue
  Kitodo-Query-URL-Import/src/main/java/org/kitodo/queryurlimport/QueryURLImport.java
Labels: security

#5855 Make pagination scope default value configureable
  Kitodo-DataManagement/src/main/java/org/kitodo/data/database/beans/User.java
  Kitodo-DataManagement/src/main/resources/db/migration/V2_128__Add_default_pagination_scope.sql
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/PaginationPanel.java
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/webapp/WEB-INF/templates/includes/userEdit/metadataEditorSettings.xhtml
Labels: feature

#5683 Remove unused part of the image management interface
  Kitodo-API/src/main/java/org/kitodo/api/imagemanagement/ImageManagementInterface.java
  Kitodo-DataManagement/src/main/java/org/kitodo/data/database/beans/Folder.java
  Kitodo-DataManagement/src/main/java/org/kitodo/data/database/beans/Task.java
  Kitodo-DataManagement/src/main/resources/db/migration/V2_129__Delete_column_imageScale.sql
  Kitodo-ImageManagement/src/main/java/org/kitodo/imagemanagement/ImageManagement.java
  Kitodo-ImageManagement/src/test/java/org/kitodo/imagemanagement/ImageManagementIT.java
  Kitodo/src/main/java/org/kitodo/production/services/command/KitodoScriptService.java
  Kitodo/src/main/java/org/kitodo/production/services/data/FolderService.java
  Kitodo/src/main/java/org/kitodo/production/services/data/TaskService.java
  Kitodo/src/main/java/org/kitodo/production/services/image/ImageGenerator.java
  Kitodo/src/main/java/org/kitodo/production/services/image/ImageService.java
Labels: improvement

#5952 [3.6] Fix DTD security issue
  Kitodo-Query-URL-Import/src/main/java/org/kitodo/queryurlimport/QueryURLImport.java
Labels: security
