Repository kitodo/kitodo-production, pull requests merged in 2024-08, with the labels that each got.

#6082 Make user project list sortable by client
  Kitodo/src/main/webapp/WEB-INF/templates/includes/userEdit/projectList.xhtml
Labels: improvement

#6106 Extracts the renaming of processes into the process service
  Kitodo/src/main/java/org/kitodo/production/forms/ProcessForm.java
  Kitodo/src/main/java/org/kitodo/production/services/data/ProcessService.java
Labels: improvement

#6186 Translate metadata keys in mass import record table header
  Kitodo/src/main/java/org/kitodo/production/forms/massimport/MassImportForm.java
Labels: bug

#6194 Update link to developer documentation.
  README.md
Labels: documentation
