Repository kitodo/kitodo-production, pull requests merged in 2024-01, with the labels that each got.

#5867 Updating Bouncy Castle dependency (security fix)
  Kitodo/pom.xml
  pom.xml
Labels: security, dependencies

#5831 Prevent NPE
  Kitodo/src/main/java/org/kitodo/production/helper/Helper.java
Labels: bug

#5845 Display tooltip instead of the overlay in preview
  Kitodo-DataManagement/src/main/java/org/kitodo/data/database/beans/Project.java
  Kitodo-DataManagement/src/main/java/org/kitodo/data/database/enums/PreviewHoverMode.java
  Kitodo-DataManagement/src/main/resources/db/migration/V2_127__Add_preview_tooltip_to_project.sql
  Kitodo/src/main/java/org/kitodo/production/forms/ProjectForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/GalleryPanel.java
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/resources/js/metadata_editor.js
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/partials/media-list-overlay.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/partials/media-list.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/projectEdit/projectEditMets.xhtml
Labels: feature

#5868 Do not try to load process table on other list pages
  Kitodo/src/main/webapp/WEB-INF/resources/js/lists.js
Labels: bug

#5865 Remove redundant filter and task status menus
  Kitodo/src/main/webapp/WEB-INF/templates/includes/tasks/taskList.xhtml
Labels: improvement

#5892 Fix Listing ST
  Kitodo/src/test/java/org/kitodo/selenium/testframework/pages/ProjectsPage.java
  Kitodo/src/test/java/org/kitodo/selenium/testframework/pages/TasksPage.java
Labels: bug

#5504 Add media partials for audio and video
  Kitodo-API/src/main/java/org/kitodo/api/dataeditor/rulesetmanagement/FunctionalDivision.java
  Kitodo-API/src/main/java/org/kitodo/api/dataformat/MediaPartial.java
  Kitodo-API/src/main/java/org/kitodo/api/dataformat/PhysicalDivision.java
  Kitodo-DataFormat/src/main/java/org/kitodo/dataformat/access/FileXmlElementAccess.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/AddDocStrucTypeDialog.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/DataEditorForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/GalleryMediaContent.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/GalleryPanel.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/MediaPartialForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/MediaPartialsPanel.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/StructurePanel.java
  Kitodo/src/main/java/org/kitodo/production/helper/metadata/MediaPartialHelper.java
  Kitodo/src/main/java/org/kitodo/production/helper/metadata/MediaPartialLogicalDivisionComparator.java
  Kitodo/src/main/java/org/kitodo/production/services/dataeditor/DataEditorService.java
  Kitodo/src/main/resources/messages/errors_de.properties
  Kitodo/src/main/resources/messages/errors_en.properties
  Kitodo/src/main/resources/messages/messages_de.properties
  Kitodo/src/main/resources/messages/messages_en.properties
  Kitodo/src/main/resources/messages/messages_es.properties
  Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
  Kitodo/src/main/webapp/WEB-INF/resources/css/pattern-library.css
  Kitodo/src/main/webapp/WEB-INF/resources/js/libs/wavesurfer/wavesurfer.esm.js
  Kitodo/src/main/webapp/WEB-INF/resources/js/metadata_editor.js
  Kitodo/src/main/webapp/WEB-INF/resources/js/modules/media_detail_audio_waveform.js
  Kitodo/src/main/webapp/WEB-INF/resources/js/modules/media_detail_media_formatted_time.js
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/dialogs/addMediaPartial.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/logicalStructure.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/partials/media-detail-audio-waveform-tools.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/partials/media-detail-media-formatted-time.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/partials/media-detail-media-partial-list.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/partials/media-detail.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/partials/media-list-content.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/partials/media-list.xhtml
  Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/physicalStructure.xhtml
  Kitodo/src/main/webapp/pages/metadataEditor.xhtml
  Kitodo/src/test/java/org/kitodo/production/forms/dataeditor/MediaPartialFormTest.java
  Kitodo/src/test/java/org/kitodo/production/forms/dataeditor/MediaPartialPanelTest.java
  pom.xml
Labels: feature

#5900 [3.6.] Updating Bouncy Castle dependency
  Kitodo/pom.xml
  pom.xml
Labels: security, dependencies

#5897 [3.6] password change fix
  Kitodo/src/main/java/org/kitodo/production/forms/UserForm.java
  Kitodo/src/main/resources/messages/errors_de.properties
  Kitodo/src/main/resources/messages/errors_en.properties
Labels: bug

#5896 [3.6] synchronize task manager
  Kitodo/src/main/java/org/kitodo/production/helper/tasks/TaskManager.java
  Kitodo/src/main/java/org/kitodo/production/helper/tasks/TaskSitter.java
Labels: bug

#5898 [3.6] Update MetsModsGoobi_to_MetsKitodo.xsl
  Kitodo/src/main/resources/xslt/MetsModsGoobi_to_MetsKitodo.xsl
Labels: improvement
