Repository kitodo/kitodo-production, pull requests merged in 2025-02, with the labels that each got.

#6366 Fix "path must include project and resource name" in Eclipse
  Kitodo-DataManagement/pom.xml
  Kitodo/pom.xml
Labels: blocking

#6396 Make use of centralized String constants
  Kitodo-API/src/main/java/org/kitodo/constants/StringConstants.java
  Kitodo-DataEditor/src/main/java/org/kitodo/dataeditor/MetsKitodoNamespacePrefixMapper.java
  Kitodo-DataEditor/src/test/java/org/kitodo/dataeditor/MetsKitodoNamespacePrefixMapperTest.java
  Kitodo-DataEditor/src/test/java/org/kitodo/dataeditor/ruleset/RulesetManagementIT.java
  Kitodo-DataFormat/src/main/java/org/kitodo/dataformat/access/DivXmlElementAccess.java
  Kitodo-DataManagement/src/main/java/org/kitodo/data/elasticsearch/Index.java
  Kitodo/src/main/java/org/kitodo/config/ConfigProject.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/CreateProcessForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/MetadataImportDialog.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessFieldedMetadata.java
  Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/DataEditorForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/massimport/AddMetadataDialog.java
  Kitodo/src/main/java/org/kitodo/production/helper/metadata/legacytypeimplementations/LegacyLogicalDocStructHelper.java
  Kitodo/src/main/java/org/kitodo/production/helper/metadata/legacytypeimplementations/LegacyPrefsHelper.java
  Kitodo/src/main/java/org/kitodo/production/interfaces/activemq/CreateNewProcessesProcessor.java
  Kitodo/src/main/java/org/kitodo/production/model/LazyDTOModel.java
  Kitodo/src/main/java/org/kitodo/production/services/calendar/CalendarService.java
  Kitodo/src/main/java/org/kitodo/production/services/command/ImportingProcess.java
  Kitodo/src/main/java/org/kitodo/production/services/data/ImportService.java
  Kitodo/src/main/java/org/kitodo/production/services/index/IndexingService.java
  Kitodo/src/main/java/org/kitodo/production/workflow/KitodoNamespaceContext.java
  Kitodo/src/test/java/org/kitodo/config/ConfigProjectTest.java
  Kitodo/src/test/java/org/kitodo/production/forms/createprocess/ProcessDetailIT.java
  Kitodo/src/test/java/org/kitodo/production/helper/ProcessHelperIT.java
  Kitodo/src/test/java/org/kitodo/production/metadata/MetadataEditorIT.java
  Kitodo/src/test/java/org/kitodo/production/services/data/DataEditorServiceIT.java
  Kitodo/src/test/java/org/kitodo/production/services/data/ImportServiceIT.java
  Kitodo/src/test/java/org/kitodo/production/services/data/MassImportServiceIT.java
Labels: improvement

#6393 [3.8] Fix NPE when importing newspaper course with metadata
  Kitodo/src/main/java/org/kitodo/production/forms/CalendarForm.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessBooleanMetadata.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessDateMetadata.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessSelectMetadata.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessSimpleMetadata.java
  Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessTextMetadata.java
  Kitodo/src/main/java/org/kitodo/production/model/bibliography/course/Course.java
  Kitodo/src/main/java/org/kitodo/production/model/bibliography/course/metadata/CountableMetadata.java
  Kitodo/src/test/java/org/kitodo/production/model/bibliography/course/CourseTest.java
Labels: bug, calendar

#6412 [3.8] Fix translation of metadata keys in mass import form
  Kitodo/src/main/java/org/kitodo/production/forms/massimport/MassImportForm.java
  Kitodo/src/main/java/org/kitodo/production/services/data/ImportService.java
Labels: bug

#6411 Fix translation of metadata keys in mass import form
  Kitodo/src/main/java/org/kitodo/production/forms/massimport/MassImportForm.java
  Kitodo/src/main/java/org/kitodo/production/services/data/ImportService.java
Labels: bug
